PROVINCE_ID_MAP = {
    "11": "Aceh",
    "12": "Sumatera Utara",
    "13": "Sumatera Barat",
    "16": "Sumatera Selatan",
    "14": "Riau",
    "21": "Kepulauan Riau",
    "15": "Jambi",
    "17": "Bengkulu",
    "18": "Lampung",
    "19": "Bangka Belitung",
    "31": "DKI Jakarta",
    "36": "Banten",
    "32": "Jawa Barat",
    "33": "Jawa Tengah",
    "34": "DI Yogyakarta",
    "35": "Jawa Timur",
    "51": "Bali",
    "61": "Kalimantan Barat",
    "62": "Kalimantan Tengah",
    "63": "Kalimantan Selatan",
    "64": "Kalimantan Timur",
    "65": "Kalimantan Utara",
    "52": "Nusa Tenggara Barat",
    "53": "Nusa Tenggara Timur",
    "71": "Sulawesi Utara",
    "72": "Sulawesi Tengah",
    "73": "Sulawesi Selatan",
    "74": "Sulawesi Tenggara",
    "75": "Gorontalo",
    "76": "Sulawesi Barat",
    "81": "Maluku",
    "82": "Maluku Utara",
    "91": "Papua",
    "92": "Papua Barat"
}

# Official 38 Indonesian provinces. Uses the short-form names matching the
# frontend's PROVINSI enum (mining/src/db/schema.ts) rather than the full
# government names (e.g. "Aceh" not "Nanggroe Aceh Darussalam"), since the
# frontend's slug maps and geojson filenames are keyed on these short forms.
OFFICIAL_PROVINCES = {
    "Aceh", "Sumatera Utara", "Sumatera Selatan", "Sumatera Barat",
    "Bengkulu", "Riau", "Kepulauan Riau", "Jambi", "Lampung", "Kepulauan Bangka Belitung",
    "Kalimantan Barat", "Kalimantan Timur", "Kalimantan Selatan", "Kalimantan Tengah",
    "Kalimantan Utara", "Banten", "Jakarta", "Jawa Barat", "Jawa Tengah",
    "Yogyakarta", "Jawa Timur", "Bali", "Nusa Tenggara Timur",
    "Nusa Tenggara Barat", "Gorontalo", "Sulawesi Barat", "Sulawesi Tengah",
    "Sulawesi Utara", "Sulawesi Tenggara", "Sulawesi Selatan", "Maluku Utara", "Maluku",
    "Papua Barat", "Papua", "Papua Tengah", "Papua Pegunungan", "Papua Selatan",
    "Papua Barat Daya",
}

# Maps scraped/variant province names (as produced by normalize_admin's
# title-case pass) to the canonical short-form name in OFFICIAL_PROVINCES.
PROVINCE_ALIASES = {
    "Nanggroe Aceh Darussalam": "Aceh",
    "Di Yogyakarta": "Yogyakarta",
    "Daerah Istimewa Yogyakarta": "Yogyakarta",
    "Bangka Belitung": "Kepulauan Bangka Belitung",
    "Sumatra Barat": "Sumatera Barat",
    "Sumatra Selatan": "Sumatera Selatan",
    "Sumatra Utara": "Sumatera Utara",
}

COMMODITY_MAP = {
    "TIMAH": "Tin",
    "BATUBARA": "Coal",
    "NICKEL": "Nickel",
    "BAUKSIT": "Bauxite",
    "EMAS": "Gold",
    "TEMBAGA": "Copper",
    "BATU GAMPING UNTUK INDUSTRI": "Limestone",
    "KERIKIL BERPASIR ALAMI (SIRTU)": "Sand, Stone, Gravel",
    "ANDESIT": "Non-Metallic Mineral",
    "ASPAL": "Non-Metallic Mineral",
    "HEMATITE": "Non-Metallic Mineral",
    "ZEOLIT": "Non-Metallic Mineral",
    "MARMER": "Non-Metallic Mineral",
    "MANGAN": "Non-Metallic Mineral",
    "BESI": "Iron",
    "KAOLIN": "Non-Metallic Mineral",
    "TANAH LIAT": "Clay",
    "LATERIT BESI": "Iron",
    "PASIR KUARSA": "Non-Metallic Mineral",
    "BATU GAMPING": "Limestone",
    "GRANIT": "Granite",
    "BIJIH BESI": "Iron",
    "CLAY": "Clay",
    "BIJIH NIKEL": "Nickel",
    "BIJIH TIMAH": "Tin",
    "BARIT": "Non-Metallic Mineral",
    "TIMAH PUTIH": "Tin",
    "PASIR TIMAH": "Tin",
    "ZIRKON": "Non-Metallic Mineral",
    "BATUAN ASPAL": "Non-Metallic Mineral",
    "KROMIT": "Non-Metallic Mineral",
    "DOLOMIT": "Limestone",
    "BATU KAPUR": "Limestone",
    "GALENA": "Non-Metallic Mineral",
    "SIRTU": "Sand, Stone, Gravel",
    "BATUPASIR": "Sand, Stone, Gravel",
    "PASIR BESI": "Iron",
    "TIMBAL": "Non-Metallic Mineral",
    "BATUGAMPING": "Limestone",
    "PASIR URUG": "Sand",
    "BATUAN (TRASS)": "Non-Metallic Mineral",
    "TIMAH HITAM": "Non-Metallic Mineral",
    "RIJANG": "Non-Metallic Mineral",
    "BATU GUNUNG QUARRY BESAR": "Sand, Stone, Gravel",
    "BATU ANDESIT": "Sand, Stone, Gravel",
    "BATU GAMPING UNTUK SEMEN": "Limestone",
    "PASIR LAUT": "Sand, Stone, Gravel",
    "GAMPING": "Limestone",
    "BATUAN": "Sand, Stone, Gravel",
    "PASIR, BATU, KERIKIL": "Sand, Stone, Gravel",
    "PASIR": "Sand, Stone, Gravel",
    "TANAH URUG": "Non-Metallic Mineral",
    "LATERIT": "Non-Metallic Mineral",
    "BATU BESI": "Iron",
    "TANAH MERAH (LATERIT)": "Non-Metallic Mineral",
    "ANTIMON": "Non-Metallic Mineral",
    "ANTIMONI": "Non-Metallic Mineral",
    "BATU GUNUNG": "Sand, Stone, Gravel",
    "BASALT": "Sand, Stone, Gravel",
    "FELDSPAR": "Non-Metallic Mineral",
    "TRAS": "Non-Metallic Mineral",
    "BATU KAPUR/ GAMPING": "Limestone",
    "PASIR PASANG": "Sand, Stone, Gravel",
    "PASIR DARAT": "Sand, Stone, Gravel",
    "KERIKIL SUNGAI": "Sand, Stone, Gravel",
    "BENTONIT": "Non-Metallic Mineral",
    "TRASS": "Non-Metallic Mineral",
    "BATU KAPUR UNTUK SEMEN": "Limestone",
    "BATU KALI": "Sand, Stone, Gravel",
    "BATU GAMPING (BATUAN)": "Limestone",
    "PERIDOTIT": "Non-Metallic Mineral",
    "PASIR BATU": "Sand, Stone, Gravel",
    "BALL CLAY": "Clay",
    "BATU LEMPUNG": "Clay",
    "BATUGAMPING UNTUK SEMEN": "Limestone",
    "BIJIH EMAS": "Gold",
    "BATU LEMPUNG (TANAH LIAT)": "Clay",
    "PASIR BANGUNAN": "Sand, Stone, Gravel",
    "SLATE": "Non-Metallic Mineral",
    "KALSIT": "Non-Metallic Mineral",
    "DIORIT": "Sand, Stone, Gravel",
    "GABRO": "Sand, Stone, Gravel",
    "FOSFAT": "Non-Metallic Mineral",
    "MOLIBDENUM": "Non-Metallic Mineral",
    "PIROFILIT": "Non-Metallic Mineral",
    "PASIR DAN BATU (SIRTU)": "Sand, Stone, Gravel",
    "BATU KUARSA": "Non-Metallic Mineral",
    "GRANODIORIT": "Sand, Stone, Gravel",
    "QUARRY BESAR": "Sand, Stone, Gravel",
    "OBSIDIAN": "Non-Metallic Mineral",
    "GAMPING UNTUK SEMEN": "Limestone",
    "SENG, TIMAH HITAM": "Non-Metallic Mineral",
    "BATU GARNET": "Non-Metallic Mineral",
    "GRAFIT": "Non-Metallic Mineral",
    "KUARSIT": "Non-Metallic Mineral",
    "MINERAL BUKAN LOGAM": "Non-Metallic Mineral",
    "BATU GUNUNG KUARI BESAR": "Sand, Stone, Gravel",
    "PERLIT": "Non-Metallic Mineral",
    "MANGAAN": "Non-Metallic Mineral",
    "NIKEL": "Nickel",
    "Bauxite": "Bauxite",
    "BATU BARA": "Coal"
}
