PROVINCE_ID_MAP = {
    "11": "Aceh",
    "12": "Sumatera Utara",
    "13": "Sumatera Barat",
    "16": "Sumatera Selatan",
    "14": "Riau",
    "21": "Kepulauan Riau",
    "15": "Jambi",
    "17": "Bengkulu",
    "18": "Lampung",
    "19": "Bangka Belitung",
    "31": "DKI Jakarta",
    "36": "Banten",
    "32": "Jawa Barat",
    "33": "Jawa Tengah",
    "34": "DI Yogyakarta",
    "35": "Jawa Timur",
    "51": "Bali",
    "61": "Kalimantan Barat",
    "62": "Kalimantan Tengah",
    "63": "Kalimantan Selatan",
    "64": "Kalimantan Timur",
    "65": "Kalimantan Utara",
    "52": "Nusa Tenggara Barat",
    "53": "Nusa Tenggara Timur",
    "71": "Sulawesi Utara",
    "72": "Sulawesi Tengah",
    "73": "Sulawesi Selatan",
    "74": "Sulawesi Tenggara",
    "75": "Gorontalo",
    "76": "Sulawesi Barat",
    "81": "Maluku",
    "82": "Maluku Utara",
    "91": "Papua",
    "92": "Papua Barat"
}