name: Weekly Commodity Price Scraper

on:
  schedule:
    # at 00:00 (midnight) on Monday
    - cron: "0 0 * * 1"
  workflow_dispatch:

jobs:
  update-commodity-table:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.12"
          enable-cache: true

      - name: Execute synchronizer.py
        run: |
          uv run synchronizer.py sync commodity_price

      - name: Pull remote changes
        run: git pull origin main

      - name: Commit updated database
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add db.sqlite
          git diff-index --quiet HEAD \
            || git commit -m "chore: weekly commodity price update of db.sqlite" --allow-empty

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
