name: Scrape - Archive - and Push Mining News Data 

on: 
  schedule: 
    - cron: '0 0 * * *' # Runs every day at midnight UTC
  workflow_dispatch: 

jobs: 
  sync: 
    runs-on: ubuntu-latest 

    steps: 
      - name: Check out code 
        uses: actions/checkout@v3
      
      - name: Set up Python 
        uses: actions/setup-python@v4 
        with: 
          python-version: '3.11'
      
      - name: Install Dependencies 
        run: |
          python -m pip install --upgrade pip
          pip install -r insider_news/requirements.txt
      
      - name: Run Mining News Scraping and Push Local
        run: python insider_news/scripts/pipeline.py --scrape --pages 1 --db db.sqlite --output mining_news

      - name: Run Archive Old News
        run: python insider_news/scripts/pipeline.py --archive

      - name: Pull Latest Changes
        run: git pull origin main

      - name: Commit and Updated database
        run: | 
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          git add db.sqlite insider_news/data/

          git diff-index --quiet HEAD \
            || git commit -m "chore: daily scrape of mining news, update db.sqlite, and archive old data" --allow-empty

      - name: Push Changes 
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main